apiVersion: v1
kind: Service
metadata:
  name: oac-backend
spec:
  selector:
    app: oac-backend-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  # type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oac-backend-app
  name: oac-backend

spec:
  progressDeadlineSeconds: 600

  selector:
    matchLabels:
      app: oac-backend-app

  template:
    metadata:
      labels:
        app: oac-backend-app

    spec:
      volumes:
        - name: backend-cfg-volume
          configMap:
            name: oac-configmap

      containers:
        - image: oac-server
          imagePullPolicy: IfNotPresent
          name: openapi-center-backend

          ports:
            - name: http
              containerPort: 8080
          envFrom:
          - configMapRef:
              name: oac-configmap
          - secretRef:
              name: oac-secrets

          env:
            - name: spring.config.additional-location
              value: /etc/application/config.yaml

          volumeMounts:
            - name: backend-cfg-volume
              mountPath: /etc/application/config.yaml
              subPath: config.yaml

      terminationGracePeriodSeconds: 3