apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-oac
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
#   backend:
#     serviceName: default-http-backend
#     servicePort: 80
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:

          service:
            name: oac-front
            port:
              number: 8020

      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: oac-backend
            port:
              number: 8080
    
