apiVersion: v1
kind: Service
metadata:
  name: oac-front
spec:
  selector:
    app: oac-front-app
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 80
  # type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oac-front-app
  name: oac-front

spec:
  replicas: 1

  selector:
    matchLabels:
      app: oac-front-app

  template:
    metadata:
      labels:
        app: oac-front-app
    spec:
      containers:
      - image: openapi-center-front
        imagePullPolicy: Never
        name: openapi-center-front

        ports: 
          - name: http
            containerPort: 80
