apiVersion: apps/v1
kind: Deployment
metadata:
  name: oaboard-backend

spec:
  selector:
    matchLabels:
      app: oaboard-backend-app

  template:
    metadata:
      labels:
        app: oaboard-backend-app

    spec:
      containers:
      - name: openapi-board-backend

        env:
          - name: db_url
            value: mysql://oab-mysql:3306/oab
          - name: db_username
            value: oab
          - name: db_password
            value: "123456"
